name: Slash-Assign Action
description: Enables a `/assign` command that allows contributors to assign themselves to issues
runs:
  using: node12
  main: dist/index.js
branding:
  icon: archive
  color: blue
inputs:
  assigned_label:
    default: slash-assigned
    description: A label that is added to issues when they're assigned, to track which issues were assigned by this action.
  required_label:
    description: If set, the issue must have this label to be assigned.
  days_until_warning:
    default: 14
    description: The span of time (in days) between a user assigning themselves to the action commenting saying it will become unassigned.
  days_until_unassign:
    default: 7
    description: The span of time (in days) between a warning (see `days_until_warning`) and the issue being unassigned automatically.
  stale_assignment_label:
    default: stale-assignment
    description: The label applied when the assignment is stale (>= `days_until_warning`).
  pin_label:
    default: pinned
    description: A label that prevents the user from being unassigned, typically for issues that are expected to take a long time.

